name: Test Clone Specific Folder

on:
  workflow_dispatch: # Allow manual trigger

jobs:
  test-clone:
    name: Test Clone Specific Folder
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout an empty repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2. Clone Upstream Repository with Sparse Checkout
      - name: Clone Specific Folder
        run: |
          set -e
          echo "Cloning upstream repository with sparse checkout..."
          
          # Clone only the structure, no files yet
          git clone --depth 1 --filter=blob:none --sparse https://github.com/hashicorp/terraform-provider-aws.git upstream-repo
          cd upstream-repo
          
          # Enable sparse-checkout and specify the folder
          git sparse-checkout init --cone
          git sparse-checkout set website/docs/r

          # Pull the specified folder
          git pull origin main

          # Debugging: List contents of the cloned directory
          echo "Listing contents of 'website/docs/r':"
          ls -R website/docs/r
          
          cd ..

      # 3. Debug Output
      - name: Debug Workspace
        run: |
          echo "Listing workspace:"
          ls -R
