name: Sync Specific Folder from Upstream

on:
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-folder:
    name: Sync Folder to Terraform Docs Repo
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your forked repo
      - name: Checkout Your Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Clone Upstream Repository with Sparse Checkout
      - name: Clone Specific Folder
        run: |
          set -e
          echo "Cloning upstream repository with sparse checkout..."
          
          # Clone only the structure, no files yet
          git clone --depth 1 --filter=blob:none --sparse https://github.com/hashicorp/terraform-provider-aws.git upstream-repo
          cd upstream-repo
          
          # Enable sparse-checkout and specify the folder
          git sparse-checkout init --cone
          git sparse-checkout set website/docs/r

          # Pull the specified folder
          git pull origin main

          # Copy the required files into your repo
          cd ..
          mkdir -p website/docs/r
          cp -r upstream-repo/website/docs/r/* website/docs/r/

      # 3. Commit and Push Changes to Your Repo
      - name: Commit and Push Changes
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Sync .md files from upstream repository"
          git push origin main
